### ISSUE TITLE
getDelegate Deprecated !

### ISSUE THREAD

**Issue by Hitexroid** [Mixiaoxiao/FastScroll-Everywhere#1]
The method getDelegate() from the type FastScrollRecyclerView is deprecated.

**Comment by Hitexroid** [comment]
sorry i didn't saw this comment
`/**
     * @deprecated use {@link #getFastScrollDelegate()} instead
     */`

**Comment by Mixiaoxiao** [comment]
@Hitexroid 

See [OverScroll-Everywhere#use-with-fastscroll-everywhere](https://github.com/Mixiaoxiao/OverScroll-Everywhere#use-with-fastscroll-everywhere)

So I changed the method getDelegate()  to getFastScrollDelegate().
